// AUTOGENERATED FILE -- DO NOT EDIT -- SEE Makefile
//
// WebGL IDL definitions scraped from the Khronos specification:
// https://www.khronos.org/registry/webgl/specs/latest/

// Copyright (c) 2019 The Khronos Group Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and/or associated documentation files (the
// "Materials"), to deal in the Materials without restriction, including
// without limitation the rights to use, copy, modify, merge, publish,
// distribute, sublicense, and/or sell copies of the Materials, and to
// permit persons to whom the Materials are furnished to do so, subject to
// the following conditions:
//
// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Materials.
//
// THE MATERIALS ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
// CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
// MATERIALS OR THE USE OR OTHER DEALINGS IN THE MATERIALS.


/* ClearBufferMask */
#define DEPTH_BUFFER_BIT               0x00000100
#define STENCIL_BUFFER_BIT             0x00000400
#define COLOR_BUFFER_BIT               0x00004000

/* BeginMode */
#define POINTS                         0x0000
#define LINES                          0x0001
#define LINE_LOOP                      0x0002
#define LINE_STRIP                     0x0003
#define TRIANGLES                      0x0004
#define TRIANGLE_STRIP                 0x0005
#define TRIANGLE_FAN                   0x0006

/* AlphaFunction (not supported in ES20) */
/*      NEVER */
/*      LESS */
/*      EQUAL */
/*      LEQUAL */
/*      GREATER */
/*      NOTEQUAL */
/*      GEQUAL */
/*      ALWAYS */

/* BlendingFactorDest */
#define ZERO                           0
#define ONE                            1
#define SRC_COLOR                      0x0300
#define ONE_MINUS_SRC_COLOR            0x0301
#define SRC_ALPHA                      0x0302
#define ONE_MINUS_SRC_ALPHA            0x0303
#define DST_ALPHA                      0x0304
#define ONE_MINUS_DST_ALPHA            0x0305

/* BlendingFactorSrc */
/*      ZERO */
/*      ONE */
#define DST_COLOR                      0x0306
#define ONE_MINUS_DST_COLOR            0x0307
#define SRC_ALPHA_SATURATE             0x0308
/*      SRC_ALPHA */
/*      ONE_MINUS_SRC_ALPHA */
/*      DST_ALPHA */
/*      ONE_MINUS_DST_ALPHA */

/* BlendEquationSeparate */
#define FUNC_ADD                       0x8006
#define BLEND_EQUATION                 0x8009
#define BLEND_EQUATION_RGB             0x8009   /* same as BLEND_EQUATION */
#define BLEND_EQUATION_ALPHA           0x883D

/* BlendSubtract */
#define FUNC_SUBTRACT                  0x800A
#define FUNC_REVERSE_SUBTRACT          0x800B

/* Separate Blend Functions */
#define BLEND_DST_RGB                  0x80C8
#define BLEND_SRC_RGB                  0x80C9
#define BLEND_DST_ALPHA                0x80CA
#define BLEND_SRC_ALPHA                0x80CB
#define CONSTANT_COLOR                 0x8001
#define ONE_MINUS_CONSTANT_COLOR       0x8002
#define CONSTANT_ALPHA                 0x8003
#define ONE_MINUS_CONSTANT_ALPHA       0x8004
#define BLEND_COLOR                    0x8005

/* Buffer Objects */
#define ARRAY_BUFFER                   0x8892
#define ELEMENT_ARRAY_BUFFER           0x8893
#define ARRAY_BUFFER_BINDING           0x8894
#define ELEMENT_ARRAY_BUFFER_BINDING   0x8895

#define STREAM_DRAW                    0x88E0
#define STATIC_DRAW                    0x88E4
#define DYNAMIC_DRAW                   0x88E8

#define BUFFER_SIZE                    0x8764
#define BUFFER_USAGE                   0x8765

#define CURRENT_VERTEX_ATTRIB          0x8626

/* CullFaceMode */
#define FRONT                          0x0404
#define BACK                           0x0405
#define FRONT_AND_BACK                 0x0408

/* DepthFunction */
/*      NEVER */
/*      LESS */
/*      EQUAL */
/*      LEQUAL */
/*      GREATER */
/*      NOTEQUAL */
/*      GEQUAL */
/*      ALWAYS */

/* EnableCap */
/* TEXTURE_2D */
#define CULL_FACE                      0x0B44
#define BLEND                          0x0BE2
#define DITHER                         0x0BD0
#define STENCIL_TEST                   0x0B90
#define DEPTH_TEST                     0x0B71
#define SCISSOR_TEST                   0x0C11
#define POLYGON_OFFSET_FILL            0x8037
#define SAMPLE_ALPHA_TO_COVERAGE       0x809E
#define SAMPLE_COVERAGE                0x80A0

/* ErrorCode */
#define NO_ERROR                       0
#define INVALID_ENUM                   0x0500
#define INVALID_VALUE                  0x0501
#define INVALID_OPERATION              0x0502
#define OUT_OF_MEMORY                  0x0505

/* FrontFaceDirection */
#define CW                             0x0900
#define CCW                            0x0901

/* GetPName */
#define LINE_WIDTH                     0x0B21
#define ALIASED_POINT_SIZE_RANGE       0x846D
#define ALIASED_LINE_WIDTH_RANGE       0x846E
#define CULL_FACE_MODE                 0x0B45
#define FRONT_FACE                     0x0B46
#define DEPTH_RANGE                    0x0B70
#define DEPTH_WRITEMASK                0x0B72
#define DEPTH_CLEAR_VALUE              0x0B73
#define DEPTH_FUNC                     0x0B74
#define STENCIL_CLEAR_VALUE            0x0B91
#define STENCIL_FUNC                   0x0B92
#define STENCIL_FAIL                   0x0B94
#define STENCIL_PASS_DEPTH_FAIL        0x0B95
#define STENCIL_PASS_DEPTH_PASS        0x0B96
#define STENCIL_REF                    0x0B97
#define STENCIL_VALUE_MASK             0x0B93
#define STENCIL_WRITEMASK              0x0B98
#define STENCIL_BACK_FUNC              0x8800
#define STENCIL_BACK_FAIL              0x8801
#define STENCIL_BACK_PASS_DEPTH_FAIL   0x8802
#define STENCIL_BACK_PASS_DEPTH_PASS   0x8803
#define STENCIL_BACK_REF               0x8CA3
#define STENCIL_BACK_VALUE_MASK        0x8CA4
#define STENCIL_BACK_WRITEMASK         0x8CA5
#define VIEWPORT                       0x0BA2
#define SCISSOR_BOX                    0x0C10
/*      SCISSOR_TEST */
#define COLOR_CLEAR_VALUE              0x0C22
#define COLOR_WRITEMASK                0x0C23
#define UNPACK_ALIGNMENT               0x0CF5
#define PACK_ALIGNMENT                 0x0D05
#define MAX_TEXTURE_SIZE               0x0D33
#define MAX_VIEWPORT_DIMS              0x0D3A
#define SUBPIXEL_BITS                  0x0D50
#define RED_BITS                       0x0D52
#define GREEN_BITS                     0x0D53
#define BLUE_BITS                      0x0D54
#define ALPHA_BITS                     0x0D55
#define DEPTH_BITS                     0x0D56
#define STENCIL_BITS                   0x0D57
#define POLYGON_OFFSET_UNITS           0x2A00
/*      POLYGON_OFFSET_FILL */
#define POLYGON_OFFSET_FACTOR          0x8038
#define TEXTURE_BINDING_2D             0x8069
#define SAMPLE_BUFFERS                 0x80A8
#define SAMPLES                        0x80A9
#define SAMPLE_COVERAGE_VALUE          0x80AA
#define SAMPLE_COVERAGE_INVERT         0x80AB

/* GetTextureParameter */
/*      TEXTURE_MAG_FILTER */
/*      TEXTURE_MIN_FILTER */
/*      TEXTURE_WRAP_S */
/*      TEXTURE_WRAP_T */

#define COMPRESSED_TEXTURE_FORMATS     0x86A3

/* HintMode */
#define DONT_CARE                      0x1100
#define FASTEST                        0x1101
#define NICEST                         0x1102

/* HintTarget */
#define GENERATE_MIPMAP_HINT            0x8192

/* DataType */
#define BYTE                           0x1400
#define UNSIGNED_BYTE                  0x1401
#define SHORT                          0x1402
#define UNSIGNED_SHORT                 0x1403
#define INT                            0x1404
#define UNSIGNED_INT                   0x1405
#define FLOAT                          0x1406

/* PixelFormat */
#define DEPTH_COMPONENT                0x1902
#define ALPHA                          0x1906
#define RGB                            0x1907
#define RGBA                           0x1908
#define LUMINANCE                      0x1909
#define LUMINANCE_ALPHA                0x190A

/* PixelType */
/*      UNSIGNED_BYTE */
#define UNSIGNED_SHORT_4_4_4_4         0x8033
#define UNSIGNED_SHORT_5_5_5_1         0x8034
#define UNSIGNED_SHORT_5_6_5           0x8363

/* Shaders */
#define FRAGMENT_SHADER                  0x8B30
#define VERTEX_SHADER                    0x8B31
#define MAX_VERTEX_ATTRIBS               0x8869
#define MAX_VERTEX_UNIFORM_VECTORS       0x8DFB
#define MAX_VARYING_VECTORS              0x8DFC
#define MAX_COMBINED_TEXTURE_IMAGE_UNITS 0x8B4D
#define MAX_VERTEX_TEXTURE_IMAGE_UNITS   0x8B4C
#define MAX_TEXTURE_IMAGE_UNITS          0x8872
#define MAX_FRAGMENT_UNIFORM_VECTORS     0x8DFD
#define SHADER_TYPE                      0x8B4F
#define DELETE_STATUS                    0x8B80
#define LINK_STATUS                      0x8B82
#define VALIDATE_STATUS                  0x8B83
#define ATTACHED_SHADERS                 0x8B85
#define ACTIVE_UNIFORMS                  0x8B86
#define ACTIVE_ATTRIBUTES                0x8B89
#define SHADING_LANGUAGE_VERSION         0x8B8C
#define CURRENT_PROGRAM                  0x8B8D

/* StencilFunction */
#define NEVER                          0x0200
#define LESS                           0x0201
#define EQUAL                          0x0202
#define LEQUAL                         0x0203
#define GREATER                        0x0204
#define NOTEQUAL                       0x0205
#define GEQUAL                         0x0206
#define ALWAYS                         0x0207

/* StencilOp */
/*      ZERO */
#define KEEP                           0x1E00
#define REPLACE                        0x1E01
#define INCR                           0x1E02
#define DECR                           0x1E03
#define INVERT                         0x150A
#define INCR_WRAP                      0x8507
#define DECR_WRAP                      0x8508

/* StringName */
#define VENDOR                         0x1F00
#define RENDERER                       0x1F01
#define VERSION                        0x1F02

/* TextureMagFilter */
#define NEAREST                        0x2600
#define LINEAR                         0x2601

/* TextureMinFilter */
/*      NEAREST */
/*      LINEAR */
#define NEAREST_MIPMAP_NEAREST         0x2700
#define LINEAR_MIPMAP_NEAREST          0x2701
#define NEAREST_MIPMAP_LINEAR          0x2702
#define LINEAR_MIPMAP_LINEAR           0x2703

/* TextureParameterName */
#define TEXTURE_MAG_FILTER             0x2800
#define TEXTURE_MIN_FILTER             0x2801
#define TEXTURE_WRAP_S                 0x2802
#define TEXTURE_WRAP_T                 0x2803

/* TextureTarget */
#define TEXTURE_2D                     0x0DE1
#define TEXTURE                        0x1702

#define TEXTURE_CUBE_MAP               0x8513
#define TEXTURE_BINDING_CUBE_MAP       0x8514
#define TEXTURE_CUBE_MAP_POSITIVE_X    0x8515
#define TEXTURE_CUBE_MAP_NEGATIVE_X    0x8516
#define TEXTURE_CUBE_MAP_POSITIVE_Y    0x8517
#define TEXTURE_CUBE_MAP_NEGATIVE_Y    0x8518
#define TEXTURE_CUBE_MAP_POSITIVE_Z    0x8519
#define TEXTURE_CUBE_MAP_NEGATIVE_Z    0x851A
#define MAX_CUBE_MAP_TEXTURE_SIZE      0x851C

/* TextureUnit */
#define TEXTURE0                       0x84C0
#define TEXTURE1                       0x84C1
#define TEXTURE2                       0x84C2
#define TEXTURE3                       0x84C3
#define TEXTURE4                       0x84C4
#define TEXTURE5                       0x84C5
#define TEXTURE6                       0x84C6
#define TEXTURE7                       0x84C7
#define TEXTURE8                       0x84C8
#define TEXTURE9                       0x84C9
#define TEXTURE10                      0x84CA
#define TEXTURE11                      0x84CB
#define TEXTURE12                      0x84CC
#define TEXTURE13                      0x84CD
#define TEXTURE14                      0x84CE
#define TEXTURE15                      0x84CF
#define TEXTURE16                      0x84D0
#define TEXTURE17                      0x84D1
#define TEXTURE18                      0x84D2
#define TEXTURE19                      0x84D3
#define TEXTURE20                      0x84D4
#define TEXTURE21                      0x84D5
#define TEXTURE22                      0x84D6
#define TEXTURE23                      0x84D7
#define TEXTURE24                      0x84D8
#define TEXTURE25                      0x84D9
#define TEXTURE26                      0x84DA
#define TEXTURE27                      0x84DB
#define TEXTURE28                      0x84DC
#define TEXTURE29                      0x84DD
#define TEXTURE30                      0x84DE
#define TEXTURE31                      0x84DF
#define ACTIVE_TEXTURE                 0x84E0

/* TextureWrapMode */
#define REPEAT                         0x2901
#define CLAMP_TO_EDGE                  0x812F
#define MIRRORED_REPEAT                0x8370

/* Uniform Types */
#define FLOAT_VEC2                     0x8B50
#define FLOAT_VEC3                     0x8B51
#define FLOAT_VEC4                     0x8B52
#define INT_VEC2                       0x8B53
#define INT_VEC3                       0x8B54
#define INT_VEC4                       0x8B55
#define BOOL                           0x8B56
#define BOOL_VEC2                      0x8B57
#define BOOL_VEC3                      0x8B58
#define BOOL_VEC4                      0x8B59
#define FLOAT_MAT2                     0x8B5A
#define FLOAT_MAT3                     0x8B5B
#define FLOAT_MAT4                     0x8B5C
#define SAMPLER_2D                     0x8B5E
#define SAMPLER_CUBE                   0x8B60

/* Vertex Arrays */
#define VERTEX_ATTRIB_ARRAY_ENABLED        0x8622
#define VERTEX_ATTRIB_ARRAY_SIZE           0x8623
#define VERTEX_ATTRIB_ARRAY_STRIDE         0x8624
#define VERTEX_ATTRIB_ARRAY_TYPE           0x8625
#define VERTEX_ATTRIB_ARRAY_NORMALIZED     0x886A
#define VERTEX_ATTRIB_ARRAY_POINTER        0x8645
#define VERTEX_ATTRIB_ARRAY_BUFFER_BINDING 0x889F

/* Read Format */
#define IMPLEMENTATION_COLOR_READ_TYPE   0x8B9A
#define IMPLEMENTATION_COLOR_READ_FORMAT 0x8B9B

/* Shader Source */
#define COMPILE_STATUS                 0x8B81

/* Shader Precision-Specified Types */
#define LOW_FLOAT                      0x8DF0
#define MEDIUM_FLOAT                   0x8DF1
#define HIGH_FLOAT                     0x8DF2
#define LOW_INT                        0x8DF3
#define MEDIUM_INT                     0x8DF4
#define HIGH_INT                       0x8DF5

/* Framebuffer Object. */
#define FRAMEBUFFER                    0x8D40
#define RENDERBUFFER                   0x8D41

#define RGBA4                          0x8056
#define RGB5_A1                        0x8057
#define RGB565                         0x8D62
#define DEPTH_COMPONENT16              0x81A5
#define STENCIL_INDEX8                 0x8D48
#define DEPTH_STENCIL                  0x84F9

#define RENDERBUFFER_WIDTH             0x8D42
#define RENDERBUFFER_HEIGHT            0x8D43
#define RENDERBUFFER_INTERNAL_FORMAT   0x8D44
#define RENDERBUFFER_RED_SIZE          0x8D50
#define RENDERBUFFER_GREEN_SIZE        0x8D51
#define RENDERBUFFER_BLUE_SIZE         0x8D52
#define RENDERBUFFER_ALPHA_SIZE        0x8D53
#define RENDERBUFFER_DEPTH_SIZE        0x8D54
#define RENDERBUFFER_STENCIL_SIZE      0x8D55

#define FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE           0x8CD0
#define FRAMEBUFFER_ATTACHMENT_OBJECT_NAME           0x8CD1
#define FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL         0x8CD2
#define FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE 0x8CD3

#define COLOR_ATTACHMENT0              0x8CE0
#define DEPTH_ATTACHMENT               0x8D00
#define STENCIL_ATTACHMENT             0x8D20
#define DEPTH_STENCIL_ATTACHMENT       0x821A

#define NONE                           0

#define FRAMEBUFFER_COMPLETE                      0x8CD5
#define FRAMEBUFFER_INCOMPLETE_ATTACHMENT         0x8CD6
#define FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT 0x8CD7
#define FRAMEBUFFER_INCOMPLETE_DIMENSIONS         0x8CD9
#define FRAMEBUFFER_UNSUPPORTED                   0x8CDD

#define FRAMEBUFFER_BINDING            0x8CA6
#define RENDERBUFFER_BINDING           0x8CA7
#define MAX_RENDERBUFFER_SIZE          0x84E8

#define INVALID_FRAMEBUFFER_OPERATION  0x0506

    /* WebGL-specific enums */
#define UNPACK_FLIP_Y_WEBGL            0x9240
#define UNPACK_PREMULTIPLY_ALPHA_WEBGL 0x9241
#define CONTEXT_LOST_WEBGL             0x9242
#define UNPACK_COLORSPACE_CONVERSION_WEBGL 0x9243
#define BROWSER_DEFAULT_WEBGL          0x9244
