//#ifdef JPP
//#include "./gl-constants-2.m"
//#else

// Extract from https://www.khronos.org/registry/webgl/specs/latest/2.0/webgl2.idl

// AUTOGENERATED FILE -- DO NOT EDIT -- SEE Makefile
//
// WebGL IDL definitions scraped from the Khronos specification:
// https://www.khronos.org/registry/webgl/specs/latest/

// Copyright (c) 2019 The Khronos Group Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and/or associated documentation files (the
// "Materials"), to deal in the Materials without restriction, including
// without limitation the rights to use, copy, modify, merge, publish,
// distribute, sublicense, and/or sell copies of the Materials, and to
// permit persons to whom the Materials are furnished to do so, subject to
// the following conditions:
//
// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Materials.
//
// THE MATERIALS ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
// CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
// MATERIALS OR THE USE OR OTHER DEALINGS IN THE MATERIALS.

const READ_BUFFER                                   = 0x0C02;
const UNPACK_ROW_LENGTH                             = 0x0CF2;
const UNPACK_SKIP_ROWS                              = 0x0CF3;
const UNPACK_SKIP_PIXELS                            = 0x0CF4;
const PACK_ROW_LENGTH                               = 0x0D02;
const PACK_SKIP_ROWS                                = 0x0D03;
const PACK_SKIP_PIXELS                              = 0x0D04;
const COLOR                                         = 0x1800;
const DEPTH                                         = 0x1801;
const STENCIL                                       = 0x1802;
const RED                                           = 0x1903;
const RGB8                                          = 0x8051;
const RGBA8                                         = 0x8058;
const RGB10_A2                                      = 0x8059;
const TEXTURE_BINDING_3D                            = 0x806A;
const UNPACK_SKIP_IMAGES                            = 0x806D;
const UNPACK_IMAGE_HEIGHT                           = 0x806E;
const TEXTURE_3D                                    = 0x806F;
const TEXTURE_WRAP_R                                = 0x8072;
const MAX_3D_TEXTURE_SIZE                           = 0x8073;
const UNSIGNED_INT_2_10_10_10_REV                   = 0x8368;
const MAX_ELEMENTS_VERTICES                         = 0x80E8;
const MAX_ELEMENTS_INDICES                          = 0x80E9;
const TEXTURE_MIN_LOD                               = 0x813A;
const TEXTURE_MAX_LOD                               = 0x813B;
const TEXTURE_BASE_LEVEL                            = 0x813C;
const TEXTURE_MAX_LEVEL                             = 0x813D;
const MIN                                           = 0x8007;
const MAX                                           = 0x8008;
const DEPTH_COMPONENT24                             = 0x81A6;
const MAX_TEXTURE_LOD_BIAS                          = 0x84FD;
const TEXTURE_COMPARE_MODE                          = 0x884C;
const TEXTURE_COMPARE_FUNC                          = 0x884D;
const CURRENT_QUERY                                 = 0x8865;
const QUERY_RESULT                                  = 0x8866;
const QUERY_RESULT_AVAILABLE                        = 0x8867;
const STREAM_READ                                   = 0x88E1;
const STREAM_COPY                                   = 0x88E2;
const STATIC_READ                                   = 0x88E5;
const STATIC_COPY                                   = 0x88E6;
const DYNAMIC_READ                                  = 0x88E9;
const DYNAMIC_COPY                                  = 0x88EA;
const MAX_DRAW_BUFFERS                              = 0x8824;
const DRAW_BUFFER0                                  = 0x8825;
const DRAW_BUFFER1                                  = 0x8826;
const DRAW_BUFFER2                                  = 0x8827;
const DRAW_BUFFER3                                  = 0x8828;
const DRAW_BUFFER4                                  = 0x8829;
const DRAW_BUFFER5                                  = 0x882A;
const DRAW_BUFFER6                                  = 0x882B;
const DRAW_BUFFER7                                  = 0x882C;
const DRAW_BUFFER8                                  = 0x882D;
const DRAW_BUFFER9                                  = 0x882E;
const DRAW_BUFFER10                                 = 0x882F;
const DRAW_BUFFER11                                 = 0x8830;
const DRAW_BUFFER12                                 = 0x8831;
const DRAW_BUFFER13                                 = 0x8832;
const DRAW_BUFFER14                                 = 0x8833;
const DRAW_BUFFER15                                 = 0x8834;
const MAX_FRAGMENT_UNIFORM_COMPONENTS               = 0x8B49;
const MAX_VERTEX_UNIFORM_COMPONENTS                 = 0x8B4A;
const SAMPLER_3D                                    = 0x8B5F;
const SAMPLER_2D_SHADOW                             = 0x8B62;
const FRAGMENT_SHADER_DERIVATIVE_HINT               = 0x8B8B;
const PIXEL_PACK_BUFFER                             = 0x88EB;
const PIXEL_UNPACK_BUFFER                           = 0x88EC;
const PIXEL_PACK_BUFFER_BINDING                     = 0x88ED;
const PIXEL_UNPACK_BUFFER_BINDING                   = 0x88EF;
const FLOAT_MAT2x3                                  = 0x8B65;
const FLOAT_MAT2x4                                  = 0x8B66;
const FLOAT_MAT3x2                                  = 0x8B67;
const FLOAT_MAT3x4                                  = 0x8B68;
const FLOAT_MAT4x2                                  = 0x8B69;
const FLOAT_MAT4x3                                  = 0x8B6A;
const SRGB                                          = 0x8C40;
const SRGB8                                         = 0x8C41;
const SRGB8_ALPHA8                                  = 0x8C43;
const COMPARE_REF_TO_TEXTURE                        = 0x884E;
const RGBA32F                                       = 0x8814;
const RGB32F                                        = 0x8815;
const RGBA16F                                       = 0x881A;
const RGB16F                                        = 0x881B;
const VERTEX_ATTRIB_ARRAY_INTEGER                   = 0x88FD;
const MAX_ARRAY_TEXTURE_LAYERS                      = 0x88FF;
const MIN_PROGRAM_TEXEL_OFFSET                      = 0x8904;
const MAX_PROGRAM_TEXEL_OFFSET                      = 0x8905;
const MAX_VARYING_COMPONENTS                        = 0x8B4B;
const TEXTURE_2D_ARRAY                              = 0x8C1A;
const TEXTURE_BINDING_2D_ARRAY                      = 0x8C1D;
const R11F_G11F_B10F                                = 0x8C3A;
const UNSIGNED_INT_10F_11F_11F_REV                  = 0x8C3B;
const RGB9_E5                                       = 0x8C3D;
const UNSIGNED_INT_5_9_9_9_REV                      = 0x8C3E;
const TRANSFORM_FEEDBACK_BUFFER_MODE                = 0x8C7F;
const MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS    = 0x8C80;
const TRANSFORM_FEEDBACK_VARYINGS                   = 0x8C83;
const TRANSFORM_FEEDBACK_BUFFER_START               = 0x8C84;
const TRANSFORM_FEEDBACK_BUFFER_SIZE                = 0x8C85;
const TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN         = 0x8C88;
const RASTERIZER_DISCARD                            = 0x8C89;
const MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS = 0x8C8A;
const MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS       = 0x8C8B;
const INTERLEAVED_ATTRIBS                           = 0x8C8C;
const SEPARATE_ATTRIBS                              = 0x8C8D;
const TRANSFORM_FEEDBACK_BUFFER                     = 0x8C8E;
const TRANSFORM_FEEDBACK_BUFFER_BINDING             = 0x8C8F;
const RGBA32UI                                      = 0x8D70;
const RGB32UI                                       = 0x8D71;
const RGBA16UI                                      = 0x8D76;
const RGB16UI                                       = 0x8D77;
const RGBA8UI                                       = 0x8D7C;
const RGB8UI                                        = 0x8D7D;
const RGBA32I                                       = 0x8D82;
const RGB32I                                        = 0x8D83;
const RGBA16I                                       = 0x8D88;
const RGB16I                                        = 0x8D89;
const RGBA8I                                        = 0x8D8E;
const RGB8I                                         = 0x8D8F;
const RED_INTEGER                                   = 0x8D94;
const RGB_INTEGER                                   = 0x8D98;
const RGBA_INTEGER                                  = 0x8D99;
const SAMPLER_2D_ARRAY                              = 0x8DC1;
const SAMPLER_2D_ARRAY_SHADOW                       = 0x8DC4;
const SAMPLER_CUBE_SHADOW                           = 0x8DC5;
const UNSIGNED_INT_VEC2                             = 0x8DC6;
const UNSIGNED_INT_VEC3                             = 0x8DC7;
const UNSIGNED_INT_VEC4                             = 0x8DC8;
const INT_SAMPLER_2D                                = 0x8DCA;
const INT_SAMPLER_3D                                = 0x8DCB;
const INT_SAMPLER_CUBE                              = 0x8DCC;
const INT_SAMPLER_2D_ARRAY                          = 0x8DCF;
const UNSIGNED_INT_SAMPLER_2D                       = 0x8DD2;
const UNSIGNED_INT_SAMPLER_3D                       = 0x8DD3;
const UNSIGNED_INT_SAMPLER_CUBE                     = 0x8DD4;
const UNSIGNED_INT_SAMPLER_2D_ARRAY                 = 0x8DD7;
const DEPTH_COMPONENT32F                            = 0x8CAC;
const DEPTH32F_STENCIL8                             = 0x8CAD;
const FLOAT_32_UNSIGNED_INT_24_8_REV                = 0x8DAD;
const FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING         = 0x8210;
const FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE         = 0x8211;
const FRAMEBUFFER_ATTACHMENT_RED_SIZE               = 0x8212;
const FRAMEBUFFER_ATTACHMENT_GREEN_SIZE             = 0x8213;
const FRAMEBUFFER_ATTACHMENT_BLUE_SIZE              = 0x8214;
const FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE             = 0x8215;
const FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE             = 0x8216;
const FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE           = 0x8217;
const FRAMEBUFFER_DEFAULT                           = 0x8218;
const UNSIGNED_INT_24_8                             = 0x84FA;
const DEPTH24_STENCIL8                              = 0x88F0;
const UNSIGNED_NORMALIZED                           = 0x8C17;
const DRAW_FRAMEBUFFER_BINDING                      = 0x8CA6; /* Same as FRAMEBUFFER_BINDING */
const READ_FRAMEBUFFER                              = 0x8CA8;
const DRAW_FRAMEBUFFER                              = 0x8CA9;
const READ_FRAMEBUFFER_BINDING                      = 0x8CAA;
const RENDERBUFFER_SAMPLES                          = 0x8CAB;
const FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER          = 0x8CD4;
const MAX_COLOR_ATTACHMENTS                         = 0x8CDF;
const COLOR_ATTACHMENT1                             = 0x8CE1;
const COLOR_ATTACHMENT2                             = 0x8CE2;
const COLOR_ATTACHMENT3                             = 0x8CE3;
const COLOR_ATTACHMENT4                             = 0x8CE4;
const COLOR_ATTACHMENT5                             = 0x8CE5;
const COLOR_ATTACHMENT6                             = 0x8CE6;
const COLOR_ATTACHMENT7                             = 0x8CE7;
const COLOR_ATTACHMENT8                             = 0x8CE8;
const COLOR_ATTACHMENT9                             = 0x8CE9;
const COLOR_ATTACHMENT10                            = 0x8CEA;
const COLOR_ATTACHMENT11                            = 0x8CEB;
const COLOR_ATTACHMENT12                            = 0x8CEC;
const COLOR_ATTACHMENT13                            = 0x8CED;
const COLOR_ATTACHMENT14                            = 0x8CEE;
const COLOR_ATTACHMENT15                            = 0x8CEF;
const FRAMEBUFFER_INCOMPLETE_MULTISAMPLE            = 0x8D56;
const MAX_SAMPLES                                   = 0x8D57;
const HALF_FLOAT                                    = 0x140B;
const RG                                            = 0x8227;
const RG_INTEGER                                    = 0x8228;
const R8                                            = 0x8229;
const RG8                                           = 0x822B;
const R16F                                          = 0x822D;
const R32F                                          = 0x822E;
const RG16F                                         = 0x822F;
const RG32F                                         = 0x8230;
const R8I                                           = 0x8231;
const R8UI                                          = 0x8232;
const R16I                                          = 0x8233;
const R16UI                                         = 0x8234;
const R32I                                          = 0x8235;
const R32UI                                         = 0x8236;
const RG8I                                          = 0x8237;
const RG8UI                                         = 0x8238;
const RG16I                                         = 0x8239;
const RG16UI                                        = 0x823A;
const RG32I                                         = 0x823B;
const RG32UI                                        = 0x823C;
const VERTEX_ARRAY_BINDING                          = 0x85B5;
const R8_SNORM                                      = 0x8F94;
const RG8_SNORM                                     = 0x8F95;
const RGB8_SNORM                                    = 0x8F96;
const RGBA8_SNORM                                   = 0x8F97;
const SIGNED_NORMALIZED                             = 0x8F9C;
const COPY_READ_BUFFER                              = 0x8F36;
const COPY_WRITE_BUFFER                             = 0x8F37;
const COPY_READ_BUFFER_BINDING                      = 0x8F36; /* Same as COPY_READ_BUFFER */
const COPY_WRITE_BUFFER_BINDING                     = 0x8F37; /* Same as COPY_WRITE_BUFFER */
const UNIFORM_BUFFER                                = 0x8A11;
const UNIFORM_BUFFER_BINDING                        = 0x8A28;
const UNIFORM_BUFFER_START                          = 0x8A29;
const UNIFORM_BUFFER_SIZE                           = 0x8A2A;
const MAX_VERTEX_UNIFORM_BLOCKS                     = 0x8A2B;
const MAX_FRAGMENT_UNIFORM_BLOCKS                   = 0x8A2D;
const MAX_COMBINED_UNIFORM_BLOCKS                   = 0x8A2E;
const MAX_UNIFORM_BUFFER_BINDINGS                   = 0x8A2F;
const MAX_UNIFORM_BLOCK_SIZE                        = 0x8A30;
const MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS        = 0x8A31;
const MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS      = 0x8A33;
const UNIFORM_BUFFER_OFFSET_ALIGNMENT               = 0x8A34;
const ACTIVE_UNIFORM_BLOCKS                         = 0x8A36;
const UNIFORM_TYPE                                  = 0x8A37;
const UNIFORM_SIZE                                  = 0x8A38;
const UNIFORM_BLOCK_INDEX                           = 0x8A3A;
const UNIFORM_OFFSET                                = 0x8A3B;
const UNIFORM_ARRAY_STRIDE                          = 0x8A3C;
const UNIFORM_MATRIX_STRIDE                         = 0x8A3D;
const UNIFORM_IS_ROW_MAJOR                          = 0x8A3E;
const UNIFORM_BLOCK_BINDING                         = 0x8A3F;
const UNIFORM_BLOCK_DATA_SIZE                       = 0x8A40;
const UNIFORM_BLOCK_ACTIVE_UNIFORMS                 = 0x8A42;
const UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES          = 0x8A43;
const UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER     = 0x8A44;
const UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER   = 0x8A46;
const INVALID_INDEX                                 = 0xFFFFFFFF;
const MAX_VERTEX_OUTPUT_COMPONENTS                  = 0x9122;
const MAX_FRAGMENT_INPUT_COMPONENTS                 = 0x9125;
const MAX_SERVER_WAIT_TIMEOUT                       = 0x9111;
const OBJECT_TYPE                                   = 0x9112;
const SYNC_CONDITION                                = 0x9113;
const SYNC_STATUS                                   = 0x9114;
const SYNC_FLAGS                                    = 0x9115;
const SYNC_FENCE                                    = 0x9116;
const SYNC_GPU_COMMANDS_COMPLETE                    = 0x9117;
const UNSIGNALED                                    = 0x9118;
const SIGNALED                                      = 0x9119;
const ALREADY_SIGNALED                              = 0x911A;
const TIMEOUT_EXPIRED                               = 0x911B;
const CONDITION_SATISFIED                           = 0x911C;
const WAIT_FAILED                                   = 0x911D;
const SYNC_FLUSH_COMMANDS_BIT                       = 0x00000001;
const VERTEX_ATTRIB_ARRAY_DIVISOR                   = 0x88FE;
const ANY_SAMPLES_PASSED                            = 0x8C2F;
const ANY_SAMPLES_PASSED_CONSERVATIVE               = 0x8D6A;
const SAMPLER_BINDING                               = 0x8919;
const RGB10_A2UI                                    = 0x906F;
const INT_2_10_10_10_REV                            = 0x8D9F;
const TRANSFORM_FEEDBACK                            = 0x8E22;
const TRANSFORM_FEEDBACK_PAUSED                     = 0x8E23;
const TRANSFORM_FEEDBACK_ACTIVE                     = 0x8E24;
const TRANSFORM_FEEDBACK_BINDING                    = 0x8E25;
const TEXTURE_IMMUTABLE_FORMAT                      = 0x912F;
const MAX_ELEMENT_INDEX                             = 0x8D6B;
const TEXTURE_IMMUTABLE_LEVELS                      = 0x82DF;

const TIMEOUT_IGNORED                              = -1;

/* WebGL-specific enums */
const MAX_CLIENT_WAIT_TIMEOUT_WEBGL                 = 0x9247;

//#endif