// Extract from https://www.khronos.org/registry/webgl/specs/latest/2.0/webgl2.idl

// AUTOGENERATED FILE -- DO NOT EDIT -- SEE Makefile
//
// WebGL IDL definitions scraped from the Khronos specification:
// https://www.khronos.org/registry/webgl/specs/latest/

// Copyright (c) 2019 The Khronos Group Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and/or associated documentation files (the
// "Materials"), to deal in the Materials without restriction, including
// without limitation the rights to use, copy, modify, merge, publish,
// distribute, sublicense, and/or sell copies of the Materials, and to
// permit persons to whom the Materials are furnished to do so, subject to
// the following conditions:
//
// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Materials.
//
// THE MATERIALS ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
// CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
// MATERIALS OR THE USE OR OTHER DEALINGS IN THE MATERIALS.

#define READ_BUFFER                                     0x0C02
#define UNPACK_ROW_LENGTH                               0x0CF2
#define UNPACK_SKIP_ROWS                                0x0CF3
#define UNPACK_SKIP_PIXELS                              0x0CF4
#define PACK_ROW_LENGTH                                 0x0D02
#define PACK_SKIP_ROWS                                  0x0D03
#define PACK_SKIP_PIXELS                                0x0D04
#define COLOR                                           0x1800
#define DEPTH                                           0x1801
#define STENCIL                                         0x1802
#define RED                                             0x1903
#define RGB8                                            0x8051
#define RGBA8                                           0x8058
#define RGB10_A2                                        0x8059
#define TEXTURE_BINDING_3D                              0x806A
#define UNPACK_SKIP_IMAGES                              0x806D
#define UNPACK_IMAGE_HEIGHT                             0x806E
#define TEXTURE_3D                                      0x806F
#define TEXTURE_WRAP_R                                  0x8072
#define MAX_3D_TEXTURE_SIZE                             0x8073
#define UNSIGNED_INT_2_10_10_10_REV                     0x8368
#define MAX_ELEMENTS_VERTICES                           0x80E8
#define MAX_ELEMENTS_INDICES                            0x80E9
#define TEXTURE_MIN_LOD                                 0x813A
#define TEXTURE_MAX_LOD                                 0x813B
#define TEXTURE_BASE_LEVEL                              0x813C
#define TEXTURE_MAX_LEVEL                               0x813D
#define MIN                                             0x8007
#define MAX                                             0x8008
#define DEPTH_COMPONENT24                               0x81A6
#define MAX_TEXTURE_LOD_BIAS                            0x84FD
#define TEXTURE_COMPARE_MODE                            0x884C
#define TEXTURE_COMPARE_FUNC                            0x884D
#define CURRENT_QUERY                                   0x8865
#define QUERY_RESULT                                    0x8866
#define QUERY_RESULT_AVAILABLE                          0x8867
#define STREAM_READ                                     0x88E1
#define STREAM_COPY                                     0x88E2
#define STATIC_READ                                     0x88E5
#define STATIC_COPY                                     0x88E6
#define DYNAMIC_READ                                    0x88E9
#define DYNAMIC_COPY                                    0x88EA
#define MAX_DRAW_BUFFERS                                0x8824
#define DRAW_BUFFER0                                    0x8825
#define DRAW_BUFFER1                                    0x8826
#define DRAW_BUFFER2                                    0x8827
#define DRAW_BUFFER3                                    0x8828
#define DRAW_BUFFER4                                    0x8829
#define DRAW_BUFFER5                                    0x882A
#define DRAW_BUFFER6                                    0x882B
#define DRAW_BUFFER7                                    0x882C
#define DRAW_BUFFER8                                    0x882D
#define DRAW_BUFFER9                                    0x882E
#define DRAW_BUFFER10                                   0x882F
#define DRAW_BUFFER11                                   0x8830
#define DRAW_BUFFER12                                   0x8831
#define DRAW_BUFFER13                                   0x8832
#define DRAW_BUFFER14                                   0x8833
#define DRAW_BUFFER15                                   0x8834
#define MAX_FRAGMENT_UNIFORM_COMPONENTS                 0x8B49
#define MAX_VERTEX_UNIFORM_COMPONENTS                   0x8B4A
#define SAMPLER_3D                                      0x8B5F
#define SAMPLER_2D_SHADOW                               0x8B62
#define FRAGMENT_SHADER_DERIVATIVE_HINT                 0x8B8B
#define PIXEL_PACK_BUFFER                               0x88EB
#define PIXEL_UNPACK_BUFFER                             0x88EC
#define PIXEL_PACK_BUFFER_BINDING                       0x88ED
#define PIXEL_UNPACK_BUFFER_BINDING                     0x88EF
#define FLOAT_MAT2x3                                    0x8B65
#define FLOAT_MAT2x4                                    0x8B66
#define FLOAT_MAT3x2                                    0x8B67
#define FLOAT_MAT3x4                                    0x8B68
#define FLOAT_MAT4x2                                    0x8B69
#define FLOAT_MAT4x3                                    0x8B6A
#define SRGB                                            0x8C40
#define SRGB8                                           0x8C41
#define SRGB8_ALPHA8                                    0x8C43
#define COMPARE_REF_TO_TEXTURE                          0x884E
#define RGBA32F                                         0x8814
#define RGB32F                                          0x8815
#define RGBA16F                                         0x881A
#define RGB16F                                          0x881B
#define VERTEX_ATTRIB_ARRAY_INTEGER                     0x88FD
#define MAX_ARRAY_TEXTURE_LAYERS                        0x88FF
#define MIN_PROGRAM_TEXEL_OFFSET                        0x8904
#define MAX_PROGRAM_TEXEL_OFFSET                        0x8905
#define MAX_VARYING_COMPONENTS                          0x8B4B
#define TEXTURE_2D_ARRAY                                0x8C1A
#define TEXTURE_BINDING_2D_ARRAY                        0x8C1D
#define R11F_G11F_B10F                                  0x8C3A
#define UNSIGNED_INT_10F_11F_11F_REV                    0x8C3B
#define RGB9_E5                                         0x8C3D
#define UNSIGNED_INT_5_9_9_9_REV                        0x8C3E
#define TRANSFORM_FEEDBACK_BUFFER_MODE                  0x8C7F
#define MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS      0x8C80
#define TRANSFORM_FEEDBACK_VARYINGS                     0x8C83
#define TRANSFORM_FEEDBACK_BUFFER_START                 0x8C84
#define TRANSFORM_FEEDBACK_BUFFER_SIZE                  0x8C85
#define TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN           0x8C88
#define RASTERIZER_DISCARD                              0x8C89
#define MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS   0x8C8A
#define MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS         0x8C8B
#define INTERLEAVED_ATTRIBS                             0x8C8C
#define SEPARATE_ATTRIBS                                0x8C8D
#define TRANSFORM_FEEDBACK_BUFFER                       0x8C8E
#define TRANSFORM_FEEDBACK_BUFFER_BINDING               0x8C8F
#define RGBA32UI                                        0x8D70
#define RGB32UI                                         0x8D71
#define RGBA16UI                                        0x8D76
#define RGB16UI                                         0x8D77
#define RGBA8UI                                         0x8D7C
#define RGB8UI                                          0x8D7D
#define RGBA32I                                         0x8D82
#define RGB32I                                          0x8D83
#define RGBA16I                                         0x8D88
#define RGB16I                                          0x8D89
#define RGBA8I                                          0x8D8E
#define RGB8I                                           0x8D8F
#define RED_INTEGER                                     0x8D94
#define RGB_INTEGER                                     0x8D98
#define RGBA_INTEGER                                    0x8D99
#define SAMPLER_2D_ARRAY                                0x8DC1
#define SAMPLER_2D_ARRAY_SHADOW                         0x8DC4
#define SAMPLER_CUBE_SHADOW                             0x8DC5
#define UNSIGNED_INT_VEC2                               0x8DC6
#define UNSIGNED_INT_VEC3                               0x8DC7
#define UNSIGNED_INT_VEC4                               0x8DC8
#define INT_SAMPLER_2D                                  0x8DCA
#define INT_SAMPLER_3D                                  0x8DCB
#define INT_SAMPLER_CUBE                                0x8DCC
#define INT_SAMPLER_2D_ARRAY                            0x8DCF
#define UNSIGNED_INT_SAMPLER_2D                         0x8DD2
#define UNSIGNED_INT_SAMPLER_3D                         0x8DD3
#define UNSIGNED_INT_SAMPLER_CUBE                       0x8DD4
#define UNSIGNED_INT_SAMPLER_2D_ARRAY                   0x8DD7
#define DEPTH_COMPONENT32F                              0x8CAC
#define DEPTH32F_STENCIL8                               0x8CAD
#define FLOAT_32_UNSIGNED_INT_24_8_REV                  0x8DAD
#define FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING           0x8210
#define FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE           0x8211
#define FRAMEBUFFER_ATTACHMENT_RED_SIZE                 0x8212
#define FRAMEBUFFER_ATTACHMENT_GREEN_SIZE               0x8213
#define FRAMEBUFFER_ATTACHMENT_BLUE_SIZE                0x8214
#define FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE               0x8215
#define FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE               0x8216
#define FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE             0x8217
#define FRAMEBUFFER_DEFAULT                             0x8218
#define UNSIGNED_INT_24_8                               0x84FA
#define DEPTH24_STENCIL8                                0x88F0
#define UNSIGNED_NORMALIZED                             0x8C17
#define DRAW_FRAMEBUFFER_BINDING                        0x8CA6 /* Same as FRAMEBUFFER_BINDING */
#define READ_FRAMEBUFFER                                0x8CA8
#define DRAW_FRAMEBUFFER                                0x8CA9
#define READ_FRAMEBUFFER_BINDING                        0x8CAA
#define RENDERBUFFER_SAMPLES                            0x8CAB
#define FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER            0x8CD4
#define MAX_COLOR_ATTACHMENTS                           0x8CDF
#define COLOR_ATTACHMENT1                               0x8CE1
#define COLOR_ATTACHMENT2                               0x8CE2
#define COLOR_ATTACHMENT3                               0x8CE3
#define COLOR_ATTACHMENT4                               0x8CE4
#define COLOR_ATTACHMENT5                               0x8CE5
#define COLOR_ATTACHMENT6                               0x8CE6
#define COLOR_ATTACHMENT7                               0x8CE7
#define COLOR_ATTACHMENT8                               0x8CE8
#define COLOR_ATTACHMENT9                               0x8CE9
#define COLOR_ATTACHMENT10                              0x8CEA
#define COLOR_ATTACHMENT11                              0x8CEB
#define COLOR_ATTACHMENT12                              0x8CEC
#define COLOR_ATTACHMENT13                              0x8CED
#define COLOR_ATTACHMENT14                              0x8CEE
#define COLOR_ATTACHMENT15                              0x8CEF
#define FRAMEBUFFER_INCOMPLETE_MULTISAMPLE              0x8D56
#define MAX_SAMPLES                                     0x8D57
#define HALF_FLOAT                                      0x140B
#define RG                                              0x8227
#define RG_INTEGER                                      0x8228
#define R8                                              0x8229
#define RG8                                             0x822B
#define R16F                                            0x822D
#define R32F                                            0x822E
#define RG16F                                           0x822F
#define RG32F                                           0x8230
#define R8I                                             0x8231
#define R8UI                                            0x8232
#define R16I                                            0x8233
#define R16UI                                           0x8234
#define R32I                                            0x8235
#define R32UI                                           0x8236
#define RG8I                                            0x8237
#define RG8UI                                           0x8238
#define RG16I                                           0x8239
#define RG16UI                                          0x823A
#define RG32I                                           0x823B
#define RG32UI                                          0x823C
#define VERTEX_ARRAY_BINDING                            0x85B5
#define R8_SNORM                                        0x8F94
#define RG8_SNORM                                       0x8F95
#define RGB8_SNORM                                      0x8F96
#define RGBA8_SNORM                                     0x8F97
#define SIGNED_NORMALIZED                               0x8F9C
#define COPY_READ_BUFFER                                0x8F36
#define COPY_WRITE_BUFFER                               0x8F37
#define COPY_READ_BUFFER_BINDING                        0x8F36 /* Same as COPY_READ_BUFFER */
#define COPY_WRITE_BUFFER_BINDING                       0x8F37 /* Same as COPY_WRITE_BUFFER */
#define UNIFORM_BUFFER                                  0x8A11
#define UNIFORM_BUFFER_BINDING                          0x8A28
#define UNIFORM_BUFFER_START                            0x8A29
#define UNIFORM_BUFFER_SIZE                             0x8A2A
#define MAX_VERTEX_UNIFORM_BLOCKS                       0x8A2B
#define MAX_FRAGMENT_UNIFORM_BLOCKS                     0x8A2D
#define MAX_COMBINED_UNIFORM_BLOCKS                     0x8A2E
#define MAX_UNIFORM_BUFFER_BINDINGS                     0x8A2F
#define MAX_UNIFORM_BLOCK_SIZE                          0x8A30
#define MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS          0x8A31
#define MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS        0x8A33
#define UNIFORM_BUFFER_OFFSET_ALIGNMENT                 0x8A34
#define ACTIVE_UNIFORM_BLOCKS                           0x8A36
#define UNIFORM_TYPE                                    0x8A37
#define UNIFORM_SIZE                                    0x8A38
#define UNIFORM_BLOCK_INDEX                             0x8A3A
#define UNIFORM_OFFSET                                  0x8A3B
#define UNIFORM_ARRAY_STRIDE                            0x8A3C
#define UNIFORM_MATRIX_STRIDE                           0x8A3D
#define UNIFORM_IS_ROW_MAJOR                            0x8A3E
#define UNIFORM_BLOCK_BINDING                           0x8A3F
#define UNIFORM_BLOCK_DATA_SIZE                         0x8A40
#define UNIFORM_BLOCK_ACTIVE_UNIFORMS                   0x8A42
#define UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES            0x8A43
#define UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER       0x8A44
#define UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER     0x8A46
#define INVALID_INDEX                                   0xFFFFFFFF
#define MAX_VERTEX_OUTPUT_COMPONENTS                    0x9122
#define MAX_FRAGMENT_INPUT_COMPONENTS                   0x9125
#define MAX_SERVER_WAIT_TIMEOUT                         0x9111
#define OBJECT_TYPE                                     0x9112
#define SYNC_CONDITION                                  0x9113
#define SYNC_STATUS                                     0x9114
#define SYNC_FLAGS                                      0x9115
#define SYNC_FENCE                                      0x9116
#define SYNC_GPU_COMMANDS_COMPLETE                      0x9117
#define UNSIGNALED                                      0x9118
#define SIGNALED                                        0x9119
#define ALREADY_SIGNALED                                0x911A
#define TIMEOUT_EXPIRED                                 0x911B
#define CONDITION_SATISFIED                             0x911C
#define WAIT_FAILED                                     0x911D
#define SYNC_FLUSH_COMMANDS_BIT                         0x00000001
#define VERTEX_ATTRIB_ARRAY_DIVISOR                     0x88FE
#define ANY_SAMPLES_PASSED                              0x8C2F
#define ANY_SAMPLES_PASSED_CONSERVATIVE                 0x8D6A
#define SAMPLER_BINDING                                 0x8919
#define RGB10_A2UI                                      0x906F
#define INT_2_10_10_10_REV                              0x8D9F
#define TRANSFORM_FEEDBACK                              0x8E22
#define TRANSFORM_FEEDBACK_PAUSED                       0x8E23
#define TRANSFORM_FEEDBACK_ACTIVE                       0x8E24
#define TRANSFORM_FEEDBACK_BINDING                      0x8E25
#define TEXTURE_IMMUTABLE_FORMAT                        0x912F
#define MAX_ELEMENT_INDEX                               0x8D6B
#define TEXTURE_IMMUTABLE_LEVELS                        0x82DF

#define TIMEOUT_IGNORED                                -1

/* WebGL-specific enums */
#define MAX_CLIENT_WAIT_TIMEOUT_WEBGL                   0x9247

